### ISSUE TITLE
Ensemble lesson: change stacking dataset

### ISSUE THREAD

**Issue by mike-ivs** [mike-ivs/machine-learning-novice-sklearn#18]
Currently we:

* Introduce Bagging using the penguin dataset
* Introduce Stacking regression using a new Diabetes dataset
* Have an exercise for Stacking classification

There's a bit of cognitive overhead in the "Stacking regression using a new Diabetes dataset" section as we introduce the new dataset as well as introduce new regressor models. The models themselves also have fairly low accuracy (~50%) and so the message that "stacking improves weaker models" can get a bit lost.

It might be worth doing one of the following:

1) Changing the Stacking regression to a Stacking classification using the Penguin Dataset (and exercise becomes regression), or
2) Changing the Stacking regression from Diabetes to the penguin dataset, and trying to fit correlations (i.e. flipper_length vs body_mass)

**Comment by NidhiGowdra** [comment]
Changed dataset to California house price regression. 
Penguins classification is added in a separate ensemble_classification.md which can be used later on if needed.
